### ISSUE TITLE
Inspect gas less settings

### ISSUE THREAD

**Issue by tak1827** [oasysgames/oasys-opstack#52]
Opstack typically charges a gas fee, but most our Verse are gasless. We've modified the code to add new gasless functionality. We need to ensure that this function is working as expected.

The flag to enable and disable the gasless feature is controlled in genesis.json. The gasless enable/disable feature is switched over time. Please review the [genesis config](https://github.com/oasysgames/oasys-op-geth/blob/main/params/config.go#L367-L370), which accepts arrays of times. As an important note, if the time is an even number, gasless is enabled; if the time is an odd number, the gasless setting is disabled.

If you're interested, please take a look at the [PR](https://github.com/oasysgames/oasys-op-geth/pull/2) for more details.

**Here are the points to check:**
- When gasless is activated
    - ensure that no gas is taken
    - the base fee should always be zero
    - the suggested gas price should also be zero.
- When gasless is disabled
    - ensure that gas is charged
    - base fee should be non-zero.
    - the suggested gas price and 
- Confirm that the scenarios of enabling gasless, then disabling gasless, and then re-enabling gasless all work fine.
    - gasless -> none gasless -> gasless again

**Comment by Sotatek-ThaoNguyen3** [comment]
@tak1827 Can you describe this task in more detail for me
